ALTER TABLE users ADD COLUMN IF NOT EXISTS occupation VARCHAR(50) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS college_name VARCHAR(200) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS company_name VARCHAR(200) DEFAULT '';
